language: python
dist: xenial  # required for Python 3.7
sudo: true    # required for Python 3.7
env:
    - REPO=tensorflow/tensorflow
    - REPO=tensorflow/agents  # has .travis.yml file
    - REPO=tensorflow/benchmarks
    - REPO=tensorflow/cleverhans  # has .travis.yml file
    - REPO=tensorflow/compression
    - REPO=tensorflow/fold
    - REPO=tensorflow/hub
    - REPO=tensorflow/kfac  # has .travis.yml file
    - REPO=tensorflow/lattice
    - REPO=tensorflow/magenta
    - REPO=tensorflow/metadata
    - REPO=tensorflow/minigo
    - REPO=tensorflow/models
    - REPO=tensorflow/moonlight  # has .travis.yml file
    - REPO=tensorflow/nmt
    - REPO=tensorflow/probability
    - REPO=tensorflow/skflow  # has .travis.yml file
    - REPO=tensorflow/tcav
    - REPO=tensorflow/tensor2tensor  # has .travis.yml file
    - REPO=tensorflow/tensorboard  # has .travis.yml file
    - REPO=tensorflow/tensorboard-plugin-example  # has .travis.yml file
    - REPO=tensorflow/tpu
    - REPO=tensorflow/transform

python:
    #- 2.7
    #- 3.6
    - 3.7
cache: pip
install:
    - pip install flake8
before_script:
    - URL=https://github.com/${REPO}
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - git clone --depth=50 ${URL} ~/${REPO}  # --branch=garden 
    - cd ~/${REPO}
script:
    - echo stop the build if there are Python syntax errors or undefined names
    - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --exit-zero --ignore=E111 --max-complexity=10 --max-line-length=127 --statistics
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
